### PR TITLE
Support Input System Package

### PR DESCRIPTION
**Pull request by mtschoen**
This PR is a companion to the [main fix](https://github.com/googlevr/cardboard/pull/345) which is made in the native plugin code. Thankfully, the fix is very simple! 🥳 

This contains some optional changes for the plugin to add a specific [`DeviceLayout`](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Layouts.html) for the Cardboard HMD. The primary benefit of this is to allow users to target bindings directly at Cardboard devices in case they have a need to differentiate it from other types of HMDs.

To be clear, the only thing needed to enable HMD tracking with the new input system is the change to the native plugin code. I'd still recommend using the extra C# code since it completes the steps described by the XR SDK documentation. Anyone using this project as an example will benefit from seeing how to implement device layouts.

### CODE REVIEW

**Comment by arilow** [comment]
The changes proposed in this PR have been tested and they work properly. They might be merged in a future release.


Thanks for your contribution to Cardboard!

**Comment by arilow** [comment]
Hi @mtschoen after doing some more testing, we found that, with these changes, the new input system does not work on iOS.


Does it work on your end?

**Comment by mtschoen** [comment]
It looks like the issue came up as a result of a bad merge, or something. All I did was rebuild the `GfxPluginCardboard.a` library and it's working again. My latest push should fix the issue.

As a side-note, it might be helpful to set up `.gitignore` entries in `googlevr/cardboard` for the files that are added by `pod install` and the XCode build process. I added a `.gitignore` to this repo to hide the `.DS_Store` files I got from opening folders on macOS.

**Comment by lneumarkt** [comment]
Hi @mtschoen! Your proposed changes have been internally merged and they will be included in the next release of Cardboard.
Thank you for your contribution to Cardboard!

**Comment by xinyunh0929** [comment]
This was merged in 1.24

**Pull request closed without merging**
