### PR TITLE
Add full VR Interaction Sample

### PR DESCRIPTION
**Pull request by joaoborks**
Following community feedback, I've created an additional sample scene containing some of the most requested features:

- VR Mode Toggle
- Non-VR Camera Controls
- Editor VR Simulation (only input, not display simulation)
- VR Interaction
- Gaze Pointer

I'll go through each one to clarify what have been done. Keep in mind that **no additional setup** is required to work with the additional sample. I just prefer disabling 'Initialize XR on Startup' on the XR Plugin Management window.

VR Mode Toggle
--- 

I've created a script named `XRCardboardController` that saves reference to the **main camera Transform** and some other objects to adjust VR or Standard mode visibility and controls. The highlights for the VR Mode Toggle System are the methods `DisableVR` on line 85 and `EnableVR` on line 106 and 108. They do precisely what is documented on the [Unity XR Management Manual](https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/index.html):

EnableVR:
```csharp
var xrManager = XRGeneralSettings.Instance.Manager;
if (!xrManager.isInitializationComplete)
    yield return xrManager.InitializeLoader();
xrManager.StartSubsystems();
Screen.sleepTimeout = SleepTimeout.NeverSleep;
```

DisableVR:
```csharp
var xrManager = XRGeneralSettings.Instance.Manager;
if (xrManager.isInitializationComplete)
{
    xrManager.StopSubsystems();
    xrManager.DeinitializeLoader();
}
cam.ResetAspect();
cam.fieldOfView = defaultFov;
cam.ResetProjectionMatrix();
cam.ResetWorldToCameraMatrix();
Screen.sleepTimeout = SleepTimeout.SystemSetting;
```

You **have** to reset the camera aspect otherwise the view will be distorted. Both `ResetProjectionMatrix()` and `ResetWorldToCameraMatrix()` only seemed necessary when working with the **Universal Render Pipeline**.

Non-VR Camera Controls
---

Also on the same script, `XRCardboardController`, it just tracks the first touch input and rotates the camera based on its delta. Check the method `CheckDrag` on line 138 and the `Update` method on lines 75 and 76.

Editor VR Simulation
---

This only simulates the VR input, not the display. It does two things: simulates the touch when not in VR, and simulates the head movement in VR. The touch simulation works almost exactly like the touch system itself, but tracks mouse position (while holding left mouse button) instead of finger movement. Check the `SimulateDrag` method on line 161. The VR head simulation, works by holding down `LeftAlt` and moving the mouse (works closely to the old cardboard plugin). If you press `Escape`, you will exit the VR mode. Check the `SimulateVR` method on line 149.

VR Interaction
---

I wanted a VR Interaction system that were simple and worked with Unity in a pretty much straightforward way. This was the best solution I could think of. It relies on the usage of Unity's [Event System](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/EventSystem.html) and [Input Modules](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/InputModules.html). I extended the base `PointerInputModule` and created the `XRCardboardInputModule`, which maps the VR center point (where you look at) as the pointer input. It works pretty straightforwardly with Unity objects. If you want to interact with physical objects (3d objects and world canvas), you need to add a `PhysicsRaycaster` component to the Main Camera and use the `Event Trigger` component and map each event to your custom script functions (precisely what I did on the sample scene). Preparing the system for gaze input, I added a time variable to send a click event after the object has been gazed for this time. So you can either look at something for a time or click with the input button, Both these settings are in a scriptable object of type `XRCardboardInputSettings` which you can adjust to your needs. I've also exposed the `OnStartHover`, `OnEndHover` and `OnClick` events to allow easier integration with existing systems. One extra thing I included, is that the Cardboard Input Module will prioritize UI objects on its raycast. This can be disabled by removing the line 46 in `XRCardboardInputModule.cs`.

Gaze Pointer
---

I recreated the original gaze pointer system from the old cardboard plugin and adapted to this VR Interaction System. From testing, I found out that setting a fixed distance and always rendering on top of everything completely removed the **duplicated gaze** view that was present on the old plugin. The Gaze Pointer is fully customizable and includes a timed progress indicator when gazing objects. It works by listening to the `XRCardboardInputModule` events. This way, the logic is handled by the `XRCardboardInputModule` and the visual feedback is handled by the `XRCardboardReticle`.

Conclusion
---

I think all of those features will help anyone migrating from the old plugin to the new one, to quickly adapt their apps with a complete environment. For those who are starting their apps with the new plugin, they will have the possibility to kickstart their development with the full VR Interaction Cycle. Please let me know if you need me to do anything else to include this in the repository.

### CODE REVIEW

**Comment by whizzkid** [comment]
I think the magic window implementation as you describe it, is not correct.  (have not tested it, since i dont use it in my project.)

But Magic window is supposed to use the rotational tracking of the phone, but only render a monoscopic view. (like AR, but with only showing the 3d scene, not overlaying it over the camera's view.)

So that you can use it as a magic window to look around into another reality so to speak :)    not rotate the view using your finger.

if it does use the phones rotation  and allows you to change it using your finger, then i've said nothing ;)

**Comment by JoaoBorks** [comment]
@whizzkid you are correct. I simply allowed camera rotation with touch. I'll update the description.

**Review by Dankann — APPROVED** [review]

**Comment by JoaoBorks** [comment]
@chaosemer @jballoffet can you guys review and give me a feedback?

**Comment by jballoffet** [comment]
Sorry for the delay here. Thanks a lot for such a great PR, @JoaoBorks. In order to allow a smooth review and a gradual merge of the proposed changes, it would be great to have them split into different PRs. I’d suggest the following schema:

- Non-VR Camera Controls
- Editor VR Simulation
- VR Interaction
- Gaze Pointer

About **VR Mode Toggle**, we have already internally added a new scene to the sample app that shows how this should be performed and it will be included in the next release.

**Comment by JoaoBorks** [comment]
Sounds good @jballoffet. I'll find a way to split into multiple PRs

**Comment by luiginicastro** [comment]
This might be a dumb question but how do I access this newer update, the version I downloaded doesn't have the Gaze pointer. I'm new to using GitHub so apologies if this is something that should be known

**Comment by JoaoBorks** [comment]
@luiginicastro you can add the package from my fork instead of the official cardboard for now: https://github.com/JoaoBorks/cardboard-xr-plugin.git#feature/xr_interaction

**Comment by luiginicastro** [comment]
@JoaoBorks thank you! Out of curiosity does this also work with UI or only with game objects?

**Comment by JoaoBorks** [comment]
@luiginicastro it works with both Game Objects (using Physics Raycaster on the Camera) and with World Canvas UI. Let me know if you need anything else.

**Comment by luiginicastro** [comment]
@JoaoBorks I have it all working when it's using the simulator (buttons and raycasts) but when I build on my device the app runs but it's not recognizing the event inputs, same happens when I switch to VR mode in the editor. For example I can gaze at the Icosahedron, which changes its color but when I tap it doesn't run the event. Any thoughts?

**Comment by JoaoBorks** [comment]
@luiginicastro are you using the sample scene from the package manager?

**Comment by luiginicastro** [comment]
@JoaoBorks Yeah I'm using HelloCardboard-Full and building it onto Android, I'm going to try on iOS as well.

**Comment by luiginicastro** [comment]
@JoaoBorks So the HelloCardboard-Full still won't work with inputs, the Hellocardboard scene does work with inputs in VR but only on GameObjects not UI World Canvas even with a physics raycaster on the camera. Sorry to be a bother on this and bloating this page with my troubleshooting

**Comment by JoaoBorks** [comment]
@luiginicastro you are right to report these issues. I'll see if I can fix it today

**Comment by JoaoBorks** [comment]
@luiginicastro I've tested the `HelloCardboard-Full` scene on both editor and device and it works as expected. What Unity version are you using?

**Comment by luiginicastro** [comment]
@JoaoBorks Oh interesting, I must have done something wrong on my end. I'm using 2019.4.17 thanks for checking though!

**Comment by StefanoCecere** [comment]
works perfect (tested now with 2020.3 LTS and Cardboard 1.4.1
it should really go into the default samples because a good Reticle isn't so easy to develop quickly.
maybe some docs or an example about the dragging would be nice

**Comment by joaoborks** [comment]
Thank you @StefanoCecere! I actually have to split this PR into multiple ones with focused content. Then I might have the opportunity to add documentation to it.

**Comment by PrathameshPrasade** [comment]
When can we expect all this good and useful stuff getting merged with the main branch?

**Comment by julyzeeta** [comment]
Hi! The HelloCardboard-Full doesn't work with UI sliders, but it works perfectly with the rest of the interface elements. Why is this happening? Please, heeelp!

Thanks!!

**Comment by julyzeeta** [comment]
Heelp pleaase! The HelloCardboard-Full doesn't work with UI sliders. Do you know why? How can i fix it?

**Comment by julyzeeta** [comment]
@joaoborks

**Comment by joaoborks** [comment]
Hi @julyzeeta sorry for my delayed response. I'll take a closer look at what you've reported. Also, if everything works fine, I'll finally split the PR into multiple, better scoped PRs so the devs can merge into the release to everyone. Allow me work a couple of days on this and I should be able to push this forward.

**Comment by QaunainM** [comment]
Hi @joaoborks , firstly thanks for making this fork.

Unfortunately, it doesn't seem to work for me, I installed this package via `Windows > Package Manager > Add Package from git URL >   https://github.com/joaoborks/cardboard-xr-plugin.git `

When I then load up the sample scene 'HelloCardboard' or 'VrMode', I get no movement or pointer. Alt and Ctrl will change the selection of the buttons at the top left of the Unity editor but nothing in the Game viewport changes.  

In VRMode I get an endless error

View a video screen recording here https://drive.google.com/file/d/1_CI960qscNbFfLofSNQ4O4LyL-Dk6VL0/view?usp=sharing

**Comment by joaoborks** [comment]
Thank you for your feedback @QaunainM ! I'll update this PR soon to improve the issues multiple people reported.

**Comment by QaunainM** [comment]
@joaoborks just letting you know in case you wanted to know the latest version of Unity that the old cardboard API  seems to work on 

In order to get the movement, gaze and reticle pointer at the date of this post I used **Unity Version 2019.4.30f1**   
+ the old Cardboard Unity SDK

**Comment by GetGitFiles** [comment]
Installed using link in Unity for Github, ticked XR and did a build, it failed the build with multiple errors. Unity 2021.

**Comment by QaunainM** [comment]
@GetGitFiles , until @joaoborks  can make a fix this is what I had to resort to https://github.com/googlevr/cardboard-xr-plugin/pull/13#issuecomment-917131987

**Comment by rev111** [comment]
I'm very interested in the gaze pointer, I can see the code in XRCardboardReticle.cs but based on naming there are apparently materials and shaders needed and I need to see how it is wired together in the scene.

> @luiginicastro you can add the package from my fork instead of the official cardboard for now: https://github.com/JoaoBorks/cardboard-xr-plugin.git#feature/xr_interaction

I created an empty 3D project and imported the package from this URL:
https://github.com/joaoborks/cardboard-xr-plugin.git

The Samples~ folder (https://github.com/joaoborks/cardboard-xr-plugin/tree/master/Samples~) that I see on the github page is missing in the package, therefore the hellocardboard scene is missing.

Should I just download the zip from github and copy it manually into the project folder?

**Comment by joaoborks** [comment]
This is weird. But if you can't import it from the package manager you should be able to get it from the package cache or by the repository and copy it manually.

**Comment by rev111** [comment]
Hey Joao, thank you very much for helping. I checked again, I think I overlooked something: After importing the package, I had to click on "Import sample". I got it working now, thanks!
I'm using Unity 2021.3.5f1 on a Mac M1. The scene with the Gaze pointer is Hello Cardboard-Full.

**Comment by AlexfongZL** [comment]
Sorry for dumb question here, why I didn't see any scene called "**Hello Cardboard-Full**"? I am using Unity 2020.3.32f1 (Window 10). The 2 scenes provided in the Samples\Google Cardboard XR Plugin for Unity\1.17.0\Hello Cardboard\Scenes are:

1. HelloCardboard.unity
2. VrMode.unity

Also, i don't see any gaze pointer as well.

**Comment by rev111** [comment]
> Sorry for dumb question here, why I didn't see any scene called "**Hello Cardboard-Full**"? I am using Unity 2020.3.32f1 (Window 10). The 2 scenes provided in the Samples\Google Cardboard XR Plugin for Unity\1.17.0\Hello Cardboard\Scenes are:
> 
> 1. HelloCardboard.unity
> 2. VrMode.unity
> 
> Also, i don't see any gaze pointer as well.

Hi AlexfongZL,
did you go into PackageManager->joaos package->samples->Import?
I missed that at first. After import, the scenes in question should be there.

**Comment by AlexfongZL** [comment]
> > Sorry for dumb question here, why I didn't see any scene called "**Hello Cardboard-Full**"? I am using Unity 2020.3.32f1 (Window 10). The 2 scenes provided in the Samples\Google Cardboard XR Plugin for Unity\1.17.0\Hello Cardboard\Scenes are:
> > 
> > 1. HelloCardboard.unity
> > 2. VrMode.unity
> > 
> > Also, i don't see any gaze pointer as well.
> 
> Hi AlexfongZL, did you go into PackageManager->joaos package->samples->Import? I missed that at first. After import, the scenes in question should be there.

Hi rev111, I import the package from this git link: https://github.com/googlevr/cardboard-xr-plugin.git
I didn't see any **joaos package** in the **Package Manager**

**Comment by joaoborks** [comment]
Hey folks, it's been 3 years since I opened this PR, and I haven't worked on it for a long time. I'll close the merge request since I do not expect to have it merged. If its features are still relevant today, I can rebuild it to today's standards. Let me know if that's the case.

**Pull request closed without merging**
